### ISSUE TITLE
Apparently date ranges are not working

### ISSUE THREAD

**Issue by crapufish** [pueteam/datasource-plugin-solr#3]
Hello

I indexed the following document (just one) in Solr (version 7.3.0):

```json
{
    "id": "/en/harry_potter_and_the_order_of_the_phoenix_2007",
    "initial_release_date": "2007-06-28",
    "name": "Harry Potter and the Order of the Phoenix",
    "genre": [
      "Family",
      "Mystery",
      "Adventure Film",
      "Fantasy",
      "Fantasy Adventure",
      "Fiction"
    ],
    "directed_by": [
      "David Yates"
    ]
  }
```

When I am trying to create a new panel in Grafana, having the 'initial_release_date' as timestamp column, I get the following error:

```json
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/1/solr/films/select?wt=json",
    "params": {
      "fq": "initial_release_date:[2013-05-07T08:58:27.382Z 2018-05-07T08:58:27.382Z]",
      "q": "*:*",
      "fl": "initial_release_date,",
      "rows": 100000,
      "sort": "initial_release_date desc"
    }
  },
  "response": {
    "responseHeader": {
      "zkConnected": true,
      "status": 400,
      "QTime": 1,
      "params": {
        "q": "*:*",
        "fl": "initial_release_date,",
        "fq": "initial_release_date:[2013-05-07T08:58:27.382Z 2018-05-07T08:58:27.382Z]",
        "sort": "initial_release_date desc",
        "rows": "100000",
        "wt": "json"
      }
    },
    "error": {
      "metadata": [
        "error-class",
        "org.apache.solr.common.SolrException",
        "root-error-class",
        "org.apache.solr.parser.ParseException"
      ],
      "msg": "org.apache.solr.search.SyntaxError: Cannot parse 'initial_release_date:[2013-05-07T08:58:27.382Z 2018-05-07T08:58:27.382Z]': Encountered \" <RANGE_GOOP> \"2018-05-07T08:58:27.382Z \"\" at line 1, column 47.\nWas expecting:\n    \"TO\" ...\n    ",
      "code": 400
    }
  }
}
```

From Solr's logs: 

```text
org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse 'initial_release_date:[2013-05-07T09:03:27.816Z 2018-05-07T09:03:27.818Z]': Encountered " <RANGE_GOOP> "2018-05-07T09:03:27.818Z "" at line 1, column 47.
Was expecting:
    "TO" ...
    
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:218)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:269)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:195)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2503)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:711)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:517)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:384)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:330)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.apache.solr.search.SyntaxError: Cannot parse 'initial_release_date:[2013-05-07T09:03:27.816Z 2018-05-07T09:03:27.818Z]': Encountered " <RANGE_GOOP> "2018-05-07T09:03:27.818Z "" at line 1, column 47.
Was expecting:
    "TO" ...
    
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:258)
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:49)
	at org.apache.solr.search.QParser.getQuery(QParser.java:169)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:207)
	... 40 more
Caused by: org.apache.solr.parser.ParseException: Encountered " <RANGE_GOOP> "2018-05-07T09:03:27.818Z "" at line 1, column 47.
Was expecting:
    "TO" ...
    
	at org.apache.solr.parser.QueryParser.generateParseException(QueryParser.java:885)
	at org.apache.solr.parser.QueryParser.jj_consume_token(QueryParser.java:767)
	at org.apache.solr.parser.QueryParser.Term(QueryParser.java:453)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:278)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:131)
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:254)
	... 43 more
```

**Comment by crapufish** [comment]
Yes, the fq param should be 
`initial_release_date:[2013-05-07T09:24:42.570Z **TO** 2018-05-07T09:24:42.570Z]`  

 (**TO** is missing)

**Comment by ishtartec** [comment]
You are absolutely right. It has been fixed. Could you pull the repo and try again?.

**Comment by ishtartec** [comment]
Thanks @crapufish

**Comment by crapufish** [comment]
Yes, now it works :-)  BTW, I am gaving Grafana 5.1.0 and, although in the plugin description is written 3.x.x, it works.

Thank you!
